### ISSUE TITLE
connection success but query failed

### ISSUE THREAD

**Issue by Jeremy001** [ianmcook/implyr#13]
hi ,I used implyr and RJDBC to connect R and impala succed, but when I use dbGetQuery to select some data from database, I got en error;

## the sql was below:
testdata <- dbGetQuery(
  impala,
  "SELECT * FROM jolly.who_orderinfo limit 10"
)

## and the error was below:
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT * FROM jolly.who_orderinfo limit 10 ([Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AuthorizationException: User '' does not have privileges to execute 'SELECT' on: jolly.who_orderinfo
), Query: SELECT * FROM jolly.who_orderinfo limit 10.)

can anyone tell me why and how can I solve this problems, thanks!

**Comment by ianmcook** [comment]
It looks like maybe the username was not passed correctly to `src_impala()`? With RJDBC, you should use one of these two methods:

```r
impala <- src_impala(drv, "jdbc:impala://host:21050", "username", "password")
```
or
```r
impala <- src_impala(drv, "jdbc:impala://host:21050;UID=username;PWD=password")
```
If you're using Kerberos, use the second method and see the [Impala JDBC driver installation guide](https://www.cloudera.com/content/www/en-us/documentation/other/connectors/impala-jdbc/latest/Cloudera-JDBC-Driver-for-Impala-Install-Guide.pdf) for details.

**Comment by Jeremy001** [comment]
My R code was below:
![image](https://user-images.githubusercontent.com/17475586/28048518-19cb030e-6624-11e7-8fe1-3274b09a6398.png)

**Comment by Jeremy001** [comment]
I give up RJDBC, use ODBC to connect impala,then "bang" sucessed!

**Comment by ianmcook** [comment]
Ok, good to hear the odbc package works. I recommend odbc over RJDBC.

**Comment by Jeremy001** [comment]
yes, thank you for your reply!
