### ISSUE TITLE
src_impala from existing connection object

### ISSUE THREAD

**Issue by dalloliogm** [ianmcook/implyr#17]
Hello,
would it be possible to simply the connection process, and initialize src_impala from an existing connection object?

For example, I already have an odbc connection initialized like this:

>  conn = odbcConnect("impaladsn")

Is there a way to call src_impala on this object directly? For example, src_impala(conn)? 

Thanks in advance.

**Comment by ianmcook** [comment]
Unfortunately I don't think this is possible. Are you creating the `conn` object using the [RODBC](https://cran.r-project.org/package=RODBC) package? RODBC is not DBI-compatible, so it does not work with dplyr and implyr. You'll need to use the newer [odbc](https://cran.r-project.org/package=odbc) package, as described in the [implyr README](https://github.com/ianmcook/implyr/blob/master/README.md).

**Comment by dalloliogm** [comment]
Thank you anyway. In my case I was able to achieve the same results with:

```
drv = odbc::odbc()
src_impala(drv=drv, dsn="impaladsn")
```

Have a nice day,
Gio

**Comment by ianmcook** [comment]
Ok, thanks!
