### ISSUE TITLE
use of impala as backend for rmarkdown-sql-codechunks supported?

### ISSUE THREAD

**Issue by henningsway** [ianmcook/implyr#21]
Today I tried to use Impala as a backend-connection to execute sql-code chunks as shown in https://rmarkdown.rstudio.com/authoring_knitr_engines.html#sql

I ran into some error message, which I will post soon. Is this feature supposed to work by any chance? It would allow sql-syntax-highlighting and increase the readability over `dbGetQuery()`. :)

I tried
```
impala <- src_impala(...)
```{sql, connection = impala}
SELECT * FROM trials
`
```

Out of curiosity: is there a conceptual or implemented difference between `DBI::dbConnect()` and `implyr::src_impala`?

**Comment by ianmcook** [comment]
It should work if you use:
```{sql, connection=impala$con}```

Explanation: knitr expects `connection` to be a DBI connection object (which inherits class `DBIConnection`) not a dplyr backend source object (which inherits class `src`). To get the connection object from a dplyr backend source object, you use `$con`.

`DBI::dbConnect()` creates a DBI connection object. `implyr::src_impala()` creates a dplyr backend, which contains an underlying DBI connection object in `$con`.

In some places in implyr, I've implemented it so that DBI connection methods called on `src_impala` objects automatically dispatch to the underlying `DBIConnection` for convenience. But in general if you need to call a DBI connection method, call it on `impala$con`.

**Comment by henningsway** [comment]
Hey Ian,

could you check this again? I just tried to execute code after running `impala <- implyr::src_impala(odbc::odbc(), "impala")`:

    ```{sql, connection = impala$con}
    <SQL-Query>
    ```

I ran into the following warning

    Error in get(options$connection, envir = globalenv()) : 
      object 'NA' not found
    Failed to execute SQL chunk

I also tried to set the `knitr`-engine explicetly by running `knitr::opts_chunk$set(connection = "impala$con")`.

Any ideas?

**Comment by ianmcook** [comment]
Without seeing your full Rmd file I can't tell why exactly it's not working, but attached here are two examples that work for me. (GitHub doesn't like .Rmd files in comments, so they're .Rmd.txt.) Example 1 uses `knitr::opts_chunk$set()` to set the connection, then just `{sql}` in at the start of the SQL block. Example 2 uses `{sql, connection=impala$con}` at the start of the SQL block.

The `connection` argument to `knitr::opts_chunk$set()` needs to be the name of a variable, not an expression like `impala$con`, so notice how in Example 1 `impala$con` is assigned to a variable named `con`.

You'll need to replace the `...` in these examples with your ODBC connection parameters.

[knitr-with-implyr-example-1.Rmd.txt](https://github.com/ianmcook/implyr/files/1812816/knitr-with-implyr-example-1.Rmd.txt)
[knitr-with-implyr-example-2.Rmd.txt](https://github.com/ianmcook/implyr/files/1812817/knitr-with-implyr-example-2.Rmd.txt)

**Comment by henningsway** [comment]
Dear Ian,

thank you for the support. Your example-files, did no not run out of the box for me (after updating the datasource-name and adjusting the sql-code). Apparently knitr likes `opts_chunk$set()` to be called in a chunk named "setup".

    ---
    title: "knitr opts_chunk$set with implyr"
    author: "Henning"
    output: html_document  # html_notebook works also
    ---
    
    ## R Markdown
    
    ```{r setup, echo=FALSE, message=FALSE, results="hide"}
    library(implyr)
    impala <- src_impala(odbc::odbc(), ...)  # add data-source names
    
    con <- impala$con
    knitr::opts_chunk$set(connection = "con")  # as you said "con" needs to be quoted
    ```
    
    ```{sql}
    SELECT * FROM flights
    ```
 
PS: I also got the other version to work, setting up the connection in the "setup" chunk seemed to do the trick here also.
