### ISSUE TITLE
copy_to limit size requirement

### ISSUE THREAD

**Issue by cderv** [ianmcook/implyr#27]
Hi, 
Is there a specific reason for `implyr` limitation of the size of data.frame that can be inserted into database ?
https://github.com/ianmcook/implyr/blob/32a3e125dc4cdbdb4f7c8822f398c0757a74a2cd/R/src_impala.R#L340-L349

I did not found any mentions in Impala Guides
https://www.cloudera.com/documentation/enterprise/5-9-x/topics/impala_create_table.html

A `DBI::dbWriteTable` on `con <- dbConnect(odbc::odbc(), "Impala_DSN")` has worked. As it is not as specific as `implyr:::db_create_table.impala_connection` , it would be better to use _implyr_ 📦 over _dbplyr_ 📦 

Thanks for advice.

**Comment by ianmcook** [comment]
Yes, this is explained [in the README under the heading **Loading Local Data into Impala**](https://github.com/ianmcook/implyr#loading-local-data-into-impala). Quoting from there:

>implyr does not provide tools for loading local data into Impala tables. This is because Impala can query data stored in several different filesystems and storage systems (HDFS, Apache HBase, Apache Kudu, Amazon S3, Microsoft ADLS, and Dell EMC Isilon) and Impala does not include built-in capability for loading local data into these systems.

> Some other dplyr backends implement the function `copy_to`, which copies a local data frame to a remote source. `implyr` implements `copy_to`, but it currently only supports very small data frames. It uses the SQL `INSERT ... VALUES()` technique, which is not suitable for loading large amounts of data.

Also see the suggestions below there in the README.

**Comment by cderv** [comment]
Yes I read the README
