### ISSUE TITLE
Error in .valueClassTest(ans, "data.frame", "dbFetch")

### ISSUE THREAD

**Issue by yaoxie** [ianmcook/implyr#34]
I'm using implyr 0.2.3, dplyr 0.7.8, dbi 0.7, dbplyr 1.2.1

The following code works

`tbl(impala, sql("select * from schema.table") ` 

but the following codes 

`tbl(impala, sql("select * from schema.table;")` 
`tbl(impala, "schema..table")`

returned an error message
`Error in .valueClassTest(ans, "data.frame", "dbFetch") : 
  invalid value from generic function ‘dbFetch’, class “character”, expected “data.frame”`

and the following code 

`tbl(impala, "schema.table")`
`tbl(impala, in_schema('schema', 'table'))` 

returned another error message
`Error: is.character(vars) is not TRUE`

**Comment by ianmcook** [comment]
Hi @yaoxie, here's what I would recommend doing to solve these errors:
- When running a command using `sql()`, leave off the semicolon at the end.
- Don't use two dots `..`  between the schema name and table name. Use only one.
- Update to implyr version 0.2.4 (the version currently on CRAN).
I think the first and second items will solve the first error you describe, and updating to 0.2.4 will solve the second error you describe. Thanks.
