### ISSUE TITLE
Add Function src_insert

### ISSUE THREAD

**Issue by BrianBorawski** [ianmcook/implyr#39]
Request a function that allows a tbl_impala, or tbl_lazy etc. to be able to be inserted back into an impala table.  
Arguments would be 
1: implyr object
2: target table (implyr object?)
3: overwrite = FALSE
4: partition spec (if it cannot be extracted automatically)

Potential Method... just a suggestion: 
After running collapse on the implyr object, $ ops contains the SQL for the query.  We just need to add the Insert Overwrite or Insert INTO statement at the beginning to make this work.

**Comment by ianmcook** [comment]
Hi Brian, I believe the existing function `compute()` does what you're looking for. (The name of this function comes from dplyr; it's not a very intuitive name.)

At the end of all your operations on the `tbl_impala`, you can use `compute()` to store the result as a new Impala table. In the call to `compute()`, you must specify `temporary = TRUE`. You can also specify other arguments, for example set `file_format = "PARQUET"` to store the new table's data as Parquet files. See the implyr [docs](https://rdrr.io/cran/implyr/man/compute.html) for details on other optional arguments.
