### ISSUE TITLE
read / write parquet / CSV files 

### ISSUE THREAD

**Issue by jkylearmstrong** [ianmcook/implyr#40]
can implyr read / write parquet files?

**Comment by ianmcook** [comment]
Short answer: Yes.

Longer answer: Impala can read and write Parquet files, and implyr can issue commands that make it do so. But Impala is not as flexible as Spark, so in many cases, it would be better to use Spark (with [sparklyr](https://spark.rstudio.com)). The intended use case for implyr is when you have access to an Impala instance and you want to use dplyr syntax to run queries on Impala tables.

If you'd like to share more details about what you're trying to achieve, I can offer more specifics.

**Comment by jkylearmstrong** [comment]
thanks for the info. 

Started doing work with sparklyr - it's a nice package. Already have a number of CSVs and parquets created using the package. However, finding that impala is much faster with querying, aggregating, and wrangling data. So my thought is to push more wrangling work into an impala workflow to gain time efficiencies. 

So now the question is  best way to now convert these files so that the workflow can be optimized.

If there are commands to read CSV or parqets into impala with implyr I could create a wrapper to pick up these files and then transition to imapla datasets. 

Once the data wrangling is complete I would pick up data back-up with sparklyr and use that to do the analysis.

**Comment by ianmcook** [comment]
To query a set of Parquet or delimited text files with Impala, you first need to create a Hive/Impala table, then load the files into the table's storage directory. The Hive/Impala table needs to be configured to expect whichever type of files you're using. More details about that can be found in our new Coursera course, [_Managing Big Data in Clusters and Cloud Storage_](https://www.coursera.org/learn/cloud-storage-big-data-analysis-sql). The specific details of how to create the tables and load the data into them depend on what kind of cluster you're using, what permissions you have on it, where you're storing table data, etc. Feel free to email me at ian at cloudera dot com and I can help with specifics.
