### ISSUE TITLE
ODBC ERROR: while contacting server - SSL connection

### ISSUE THREAD

**Issue by martinocrippa** [ianmcook/implyr#41]
Good Morning,

i'm trying to connect to Impala, but i received:
`Error: nanodbc/nanodbc.cpp:950: HY000: [Cloudera][ThriftExtension] (5) Error occurred while contacting server: No more data to read.. This could be because you are trying to establish a non-SSL connection to a SSL-enabled server.`

My connection code is:
`impala <- src_impala(
    drv = drv,
    driver = "Cloudera ODBC Driver for Impala",
    host = "server.ita.it",
    port = 21050,
    database = "dwh",
    uid = userId,
    pwd = password
)`
i thought the problem was to check SSL connection, but my cloudera ODBC have check "ENABLE SSL" on setting and if i connect to IMPALA with DBI library i haven't . DBI connection code:
`conHD <- DBI::dbConnect(odbc::odbc(),
                        SERVER_NAME_HDP, # CLODERA ODBC NAME
                        uid = userIdHdp,
                        pwd = passwordHdp)`

where am I wrong?

R session info:

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] odbc_1.1.6   implyr_0.3.0 dplyr_0.8.3  DBI_1.0.0   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.2       zeallot_0.1.0    dbplyr_1.4.2     crayon_1.3.4     assertthat_0.2.1 R6_2.4.0         backports_1.1.5  magrittr_1.5     pillar_1.4.2    
> [10] rlang_0.4.0      rstudioapi_0.10  blob_1.2.0       vctrs_0.2.0      tools_3.6.1      bit64_0.9-7      glue_1.3.1       bit_1.1-14       purrr_0.3.2     
> [19] hms_0.5.1        compiler_3.6.1   pkgconfig_2.0.3  tidyselect_0.2.5 tibble_2.1.3
with:
> Cloudera ODBC Driver for Impala version 2.5.59

thanks in advance
have nice day
MC

**Comment by ianmcook** [comment]
Hi Martino, Does the instance of Impala that you are connecting to use Kerberos for authentication?

**Comment by martinocrippa** [comment]
Hi Iam,

yes the istance use Kerberos.

I study my impala odbc and i saw that there's an option to "allow SSL connection". Studying the problem i undestand that DBI read the information about SSL connection from odbc driver. 
At the end I saw that DBI connection command have a parameter for cloudera impala driver name between quote. 

I read the code of "src_impala" function and i try to insert the same in your function:
`impala <- src_impala("ODBC_CLOUDERA_IMPALA_DRIVERS_NAME", drv = drv, driver = "Cloudera ODBC Driver for Impala", host = "server.ita.it", port = 21050, database = "dwh", uid = userId, pwd = password )`
and the connection start.

I think the problem was mine, i misunderstand to read the documentation.

Thank you very much
have nice day

MC

**Comment by ianmcook** [comment]
Great, I'm happy to hear you were able to get it working!
