### ISSUE TITLE
Translating expression with extracted entry. 

### ISSUE THREAD

**Issue by Diego-MX** [ianmcook/implyr#44]
I think I found a bug, although I cannot be sure that it is still present. 
I'll mention it here because it's simple, and if needed and relevant I'll work on a reproducible example. 

I am calculating a range of dates by which to filter my main frame.  Let's just take the whole weeks.  
And using that to filter the table. 
```{R}
> dates_range <- tbl(conn, "events") %>%
    group_by(a_week = floor_date(a_date, "week")) %>% 
    mutate(n_days = n()) %>% 
    select(a_week, a_date) %>% distinct() %>%  collect() %>%
    filter(n_days == 7) %$% 
    range(a_date) %>% as.Date()

> events_query <- tbl(conn, "events") %>% 
    filter(a_date >= dates_range[1]) %>% show_query()
```

I get 
```{SQL}
SELECT *
FROM `events`
WHERE (`a_date` >= CASE 
  WHEN (1.0) THEN (('2020-05-04', '2020-06-21')) 
  END)
```

Thus it's interpreting `date_range[1]` as a `CASE WHEN` clause, which does weird things. 
While for my purpose I can go around and substitue the `date_range` value, I thought to write it here and do my share. 

I must say, that I wasn't able to download the latest version of `implyr` since I'm on a work computer, and thus find a possibility of this being fixed already.  😮 

Regards from Mexico.

**Comment by ianmcook** [comment]
Hi @Diego-MX, I'll take a look at this within a few days! Thank you

**Comment by Diego-MX** [comment]
I think this is more of the dbplyr engine thing than it is specific about implyr.

I am looking more closely to set the ticket there.

Thanks for the work, and ill come back if I find anything

**Comment by ianmcook** [comment]
@Diego-MX what happens if you change `date_range[1]` into a character string with `as.character(dates_range[1])`? Does that change the resulting SQL?

**Comment by ianmcook** [comment]
@Diego-MX I investigated this and you're correct that it's a general dbplyr issue, not an implyr-specific issue. dbplyr seems to be misinterpreting the square bracket operator inside the `filter()` call. The solution is to do something like this, to put the `[1]` outside of the `filter()`:
```r
earliest_date <- dates_range[1]
tbl(conn, "events") %>% filter(a_date >= earliest_date) %>% show_query()
```
