### ISSUE TITLE
dbplyr 2.0.0 breaks implyr

### ISSUE THREAD

**Issue by karoliskascenas** [ianmcook/implyr#48]
Unfortunately I cannot paste any output as I have already downgraded to `1.4.4`, but the problem was that "db.tbl" was not being properly escaped when using `tbl(impala, "db.tbl")` or `tbl(impala, in_schema("db", "tbl"))`.

The only way I was able to query data was with `dbGetQuery(impala, "select * from db.tbl")` where the query string was probably not being manipulated in any way.

I am quite inexperienced with R, but maybe a quick fix would be to cap the dbplyr version dependency on `1.4.4`?

**Comment by ianmcook** [comment]
Thanks. I hope to find time very soon to update the package for dbplyr 2.0.0 compatibility

**Comment by ianmcook** [comment]
@karoliskascenas are you using the ODBC or JDBC driver for Impala?

**Comment by karoliskascenas** [comment]
JDBC

**Comment by ianmcook** [comment]
The problem seems to be that a change in dbplyr caused`DBI::dbQuoteIdentifier()` to use double quotes (` " `) instead of backticks (``` ` ```) to quote table and column names. I believe this is fixed in 92c79de.
