### ISSUE TITLE
Issues integrating with dbplyr 2.4.0

### ISSUE THREAD

**Issue by whipson** [ianmcook/implyr#59]
Upgrading `dbplyr` to the latest version 2.3.4 -> **2.4.0** caused previously working queries to fail. 

```
impala <- DBI::dbConnect(odbc::odbc(), "Impala")
dplyr::tbl(impala, "reference.seat_capacity")

It looks like you tried to incorrectly use a table in a schema as source.
ℹ If you want to specify a schema use `in_schema()` or `in_catalog()`.
ℹ If your table actually contains "." in the name use `check_from = FALSE` to
  silence this message.
Error in `as.character()`:
! Can't convert `x` <dbplyr_table_ident> to <character>.
Run `rlang::last_trace()` to see where the error occurred.
```

I originally posted this issue in `dbplyr` but was informed by the developers there that it's an `implyr` issue. See original issue [here](https://github.com/tidyverse/dbplyr/issues/1388#issuecomment-1790630936)

**Comment by ianmcook** [comment]
implyr 0.5.0 is now on CRAN. I think it solves the failures with dbplyr 2.4.0. At some point implyr needs a bigger overhaul to make it properly compatible with the latest dplyr and dbplyr APIs. For now I hope the band-aid fixes help.
